apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "kubernetes-cost-attribution"
  labels:
    app.kubernetes.io/name: "kubernetes-cost-attribution"
spec:
  type: "kubernetes-cost-attribution"
  selector:
    matchLabels:
     app.kubernetes.io/name: "kubernetes-cost-attribution"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: StatefulSet
  version: "1.0.0"
  description: "An appliction that helps you put a cost on a namespace based on the machines it is running on."
  icons:
    - src: "https://s.w.org/style/images/about/WordPress-logotype-wmark.png"
      type: "image/png"
      size: "1000x1000"
    - src: "https://s.w.org/style/images/about/WordPress-logotype-standard.png"
      type: "image/png"
      size: "2000x680"
  maintainers:
    - name: Garland Kan
      email: garland@managedkube.com
  owners:
    - name: Garland Kan
      email: garland@managedkube.com
  keywords:
   - "cost"
   - "cloud"
   - "usage"
  links:
    - description: About
      url: "https://www.managedkube.com/about"
