applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  billingImage:
    type: string
    default: gcr.io/managedkube/kubernetes-cost-attribution:1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: billing.image.repository
            after: billing.image.tag
  ubbAgentImage:
    type: string
    default: gcr.io/managedkube/kubernetes-cost-attribution/ubbagent:1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: billing.ubbAgent.image.repository
            after: billing.ubbAgent.image.tag
  controller.serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- name
- namespace
- controller.serviceAccount
