applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  wordpressImage:
    type: string
    default: gcr.io/partner-project/wordpress:1.0
    x-google-marketplace:
      type: IMAGE
  ubbAgentImage:
    type: string
    default: gcr.io/partner-project/wordpress/ubbagent:1.0
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
