---
namespace: gar

enableGCEBillingAgent: true

billing:
  image:
    repository: gcr.io/managedkube/kubernetes-cost-attribution
    tag: refactor-namespaces
    pullPolicy: Always
    #pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 250Mi

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.2.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 4000m
      memory: 4000Mi
    requests:
      cpu: 250m
      memory: 250Mi

kubeStateMetrics:
  image:
    repository: k8s.gcr.io/kube-state-metrics
    tag: v1.3.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi

grafana:
  image:
    repository: grafana/grafana
    tag: 5.1.2
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi
  credentials:
    user: admin
    password: kube-cost-attribution
