# example: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/614cea698f6974eb1c5aaeaee714b4631a0f3eee/k8s/cassandra/manifest/application.yaml.template#L88
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Wordpress
    versions: '6'
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  - group: apps/v1beta2
    kind: StatefulSet
