application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecretName:     # Any name you would like to use, really.
    type: string
    x-google-marketplace:  # This is the annotation that identifies the property.
      type: REPORTING_SECRET
required:
- name
- namespace
