---
apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: {{ .Values.namespace }}
  labels:
    app: billing
  annotations:
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9101
    protocol: TCP
  selector:
    app: billing
