---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: "{{ .Values.calculator.image.repository }}:{{ .Values.calculator.image.tag }}"
        command:
          - "sh"
        args:
          - "-c"
          - |
            python3 pod_usage.py https://prometheus.dev.us-east-1.k8s.tillster.com tillster-kube ecOKg7edlfAgVyPx+bLSHu0 /opt/cost-attribution-output/billing-managed-kube.csv /opt/last-state/last_state.json 3
            python3 billing_summary.py /opt/cost-attribution-output/billing-managed-kube.csv
            echo "----Completed----"
            sleep 99999
        env:
          - name: NAME
            value: "prod.us-east-1"
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"
        imagePullPolicy: "{{ .Values.calculator.image.pullPolicy }}"
        volumeMounts:
        - mountPath: /opt/last-state
          name: last-state
      volumes:
      - name: last-state
        configMap:
          name: last-state
