---
apiVersion: v1
kind: Service
metadata:
  name: calculator
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: calculator
