---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 300
      nodeSelector:
        k8s.info/application: infrastructure

      initContainers:
      - name: init-directory
        image: busybox
        imagePullPolicy: Always
        command:
        - "sh"
        - "-c"
        - "mkdir -p /data/prometheus-data; chmod -R 777 /data/prometheus-data;"
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 50mi
        #   requests:
        #     cpu: 10m
        #     memory: 25Mi
        volumeMounts:
        - name: datadir
          mountPath: /data

      containers:
      - name: prometheus
        image: prom/prometheus:v2.2.1
        args: [
          "--config.file=/etc/prometheus/config/config.yml",
          "--web.external-url=http://prometheus.prod-1.infra.devops.bot",
          "--web.enable-lifecycle",
          "--storage.tsdb.path=/data/prometheus-data",
          "--storage.tsdb.retention=90d",

        ]
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/config
        # - name: rules
        #   mountPath: /etc/prometheus/rules
        - name: datadir
          mountPath: /data
        resources:
          limits:
            cpu: 8000m
            memory: 8000Mi
          requests:
            cpu: 250m
            memory: 250Mi
      - name: configmap-reload
        image: quay.io/coreos/configmap-reload:v0.0.1 # https://github.com/jimmidyson/configmap-reload
        args: [
          "-webhook-url=http://localhost:9090/-/reload",
          "-volume-dir=/etc/prometheus/config"
        ]
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/config
          readOnly: true
        # - name: rules
        #   mountPath: /etc/prometheus/rules
        #   readOnly: true
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: datadir
        emptyDir: {}
      # - name: rules
      #   configMap:
      #     name: prometheus-rules
      # - name: datadir
      #   persistentVolumeClaim:
      #     claimName: efs-prometheus
