---
namePrefix: cost-attribution

enableGCEBillingAgent: true

createNamespace: true
namespace: kubernetes-cost-attribution

enableRBAC: false
enableRBACGoogleMarketPlace: true

billing:
  image:
    repository: gcr.io/managedkube/kubernetes-cost-attribution
    tag: refactor-namespaces
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 250Mi
  ubbAgent:
    enable: false
    image:
      repository: gcr.io/cloud-marketplace-tools/metering/ubbagent
      tag: sha_dfb8b727bd23a7e48b6b4904f4fa2aad43634607
      pullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 25Mi
prometheus:
  image:
    repository: prom/prometheus
    tag: v2.2.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 4000m
      memory: 4000Mi
    requests:
      cpu: 250m
      memory: 250Mi
  disk:
    size: 50Gi
  dataRetention: 60d

kubeStateMetrics:
  image:
    repository: k8s.gcr.io/kube-state-metrics
    tag: v1.3.1
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi

grafana:
  image:
    repository: grafana/grafana
    tag: 5.1.2
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi
  credentials:
    user: admin
    password: kube-cost-attribution
  ingress:
    enable: false
    ingressClass: nginx
    enableTlsAcme: true
    hostname: kca.demo.devops.bot
    annotations:
      enable: false
      whitelistSourceRange: "1.1.1.1/32,2.2.2.2/32"
