---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kca-prometheus-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: kca-prometheus
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kca-prometheus
  namespace: {{ .Values.namespace }}
