---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-prometheus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: {{ .Values.namePrefix }}-prometheus
      terminationGracePeriodSeconds: 300
      # nodeSelector:
      #   k8s.info/application: infrastructure

      initContainers:
      - name: init-directory
        image: busybox
        imagePullPolicy: Always
        command:
        - "sh"
        - "-c"
        - "mkdir -p /data/prometheus-data; chmod -R 777 /data/prometheus-data;"
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 50mi
        #   requests:
        #     cpu: 10m
        #     memory: 25Mi
        volumeMounts:
        - name: datadir
          mountPath: /data

      containers:
      - name: prometheus
        image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
        imagePullPolicy: "{{ .Values.prometheus.image.pullPolicy }}"
        args: [
          "--config.file=/etc/prometheus/config/config.yml",
          "--web.external-url=http://prometheus.prod-1.infra.devops.bot",
          "--web.enable-lifecycle",
          "--storage.tsdb.path=/data/prometheus-data",
          "--storage.tsdb.retention=90d",

        ]
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/config
        # - name: rules
        #   mountPath: /etc/prometheus/rules
        - name: datadir
          mountPath: /data
        resources:
          limits:
            cpu: {{ .Values.prometheus.resources.limits.cpu }}
            memory: {{ .Values.prometheus.resources.limits.memory }}
          requests:
            cpu: {{ .Values.prometheus.resources.requests.cpu }}
            memory: {{ .Values.prometheus.resources.requests.memory }}

      volumes:
      - name: config
        configMap:
          name: {{ .Values.namePrefix }}-prometheus-config
      - name: datadir
        emptyDir: {}
      # - name: rules
      #   configMap:
      #     name: prometheus-rules
      # - name: datadir
      #   persistentVolumeClaim:
      #     claimName: efs-prometheus
